/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CS2.h
**     Project   : debug_test
**     Processor : MC9S12XEP100MAL
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.035
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 11/01/2019, 14:17
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       96            |  PS7_SS0
**             ----------------------------------------------------
**
**         Port name                   : S
**
**         Bit number (in port)        : 7
**         Bit mask of the port        : $0080
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : PTS       [$0248]
**         Port control register       : DDRS      [$024A]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool CS2_GetVal(void);
**         PutVal - void CS2_PutVal(bool Val);
**         ClrVal - void CS2_ClrVal(void);
**         SetVal - void CS2_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef CS2_H_
#define CS2_H_

/* MODULE CS2. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG CS2_CODE
/*
** ===================================================================
**     Method      :  CS2_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define CS2_GetVal() ( \
    (bool)((getReg8(PTS) & 0x80U))     /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  CS2_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void CS2_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  CS2_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define CS2_ClrVal() ( \
    (void)clrReg8Bits(PTS, 0x80U)      /* PTS7=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  CS2_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define CS2_SetVal() ( \
    (void)setReg8Bits(PTS, 0x80U)      /* PTS7=0x01U */ \
  )

#pragma CODE_SEG DEFAULT

/* END CS2. */
#endif /* #ifndef __CS2_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
