/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SPI_2.c
**     Project   : debug_test
**     Processor : MC9S12XEP100MAL
**     Component : SynchroMaster
**     Version   : Component 02.341, Driver 01.20, CPU db: 3.00.035
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 20/03/2019, 14:07
**     Abstract  :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings  :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI0
**
**         Protocol
**             Init baud rate          : 500kHz
**             Clock edge              : falling
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI0DR    [$00DC]
**             Output buffer           : SPI0DR    [$00DC]
**             Control register        : SPI0CR1   [$00D8]
**             Mode register           : SPI0CR2   [$00D9]
**             Baud setting reg.       : SPI0BR    [$00DA]
**
**         Input interrupt
**             Vector name             : Vspi0
**             Priority                : 4
**
**         Output interrupt
**             Vector name             : Vspi0
**             Priority                : 4
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     93     |  PS4_MISO0
**               Output     |     94     |  PS5_MOSI0
**               Clock      |     95     |  PS6_SCK0
**         ----------------------------------------------------------
**
**     Contents  :
**         RecvChar        - byte SPI_2_RecvChar(SPI_2_TComData *Chr);
**         SendChar        - byte SPI_2_SendChar(SPI_2_TComData Chr);
**         RecvBlock       - byte SPI_2_RecvBlock(SPI_2_TComData *Ptr, word Size, word *Rcv);
**         SendBlock       - byte SPI_2_SendBlock(SPI_2_TComData *Ptr, word Size, word *Snd);
**         ClearRxBuf      - byte SPI_2_ClearRxBuf(void);
**         ClearTxBuf      - byte SPI_2_ClearTxBuf(void);
**         GetCharsInRxBuf - word SPI_2_GetCharsInRxBuf(void);
**         GetCharsInTxBuf - word SPI_2_GetCharsInTxBuf(void);
**         GetError        - byte SPI_2_GetError(SPI_2_TError *Err);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE SPI_2. */

#include "SPI_2.h"
#include "SPI_1.h"
#include "TI1.h"
#include "TI2.h"
#include "CS1.h"
#include "CS2.h"
#include "CAN1.h"
#include "Events.h"

#pragma DATA_SEG SPI_2_DATA            /* Select data segment "SPI_2_DATA" */
#pragma CODE_SEG SPI_2_CODE


#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */

static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Unused */
static byte ErrFlag;                   /* Error flags mirror of SerFlag */
word SPI_2_InpLen;                     /* Length of input buffer's content */
static SPI_2_TComData *InpPtrR;        /* Pointer for reading from input buffer */
static SPI_2_TComData *InpPtrW;        /* Pointer for writing to input buffer */
static SPI_2_TComData InpBuffer[SPI_2_INP_BUF_SIZE]; /* Input buffer SPI commmunication */
word SPI_2_OutLen;                     /* Length of output bufer's content */
static SPI_2_TComData *OutPtrR;        /* Pointer for reading from output buffer */
static SPI_2_TComData *OutPtrW;        /* Pointer for writing to output buffer */
static SPI_2_TComData OutBuffer[SPI_2_OUT_BUF_SIZE]; /* Output buffer for SPI commmunication */
static bool OnFreeTxBuf_semaphore;     /* Disable the false calling of the OnFreeTxBuf event */

/*
** ===================================================================
**     Method      :  SPI_2_RecvChar (component SynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. If interrupt service
**                           is enabled, and input buffer allocated by
**                           the component is full, the component
**                           behaviour depends on <Input buffer size>
**                           property : if property is 0, last received
**                           data-word is preserved (and previous is
**                           overwritten), if property is greater than 0,
**                           new received data-word are ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte SPI_2_RecvChar(SPI_2_TComData *Chr)
{
  byte FlagTmp;

  if (SPI_2_InpLen > 0U) {             /* Is number of received chars greater than 0? */
    EnterCritical();                   /* Enter the critical section */
    SPI_2_InpLen--;                    /* Decrease number of received chars */
    *Chr = *(InpPtrR++);               /* Read the char */
    /*lint -save  -e946 Disable MISRA rule (17.2) checking. */
    if (InpPtrR >= (InpBuffer + SPI_2_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrR = InpBuffer;             /* Set pointer to the first item into the receive buffer */
    }
    /*lint -restore Enable MISRA rule (17.2) checking. */
    FlagTmp = SerFlag;                 /* Safe the flags */
    SerFlag &= (byte)(~(byte)(OVERRUN_ERR | FULL_RX)); /* Clear flag "char in RX buffer" */
    ExitCritical();                    /* Exit the critical section */
  } else {
    return ERR_RXEMPTY;                /* Receiver is empty */
  }
  if ((FlagTmp & (OVERRUN_ERR | FULL_RX)) != 0U) { /* Is the overrun occured? */
    return ERR_OVERRUN;                /* If yes then return error */
  } else {
    return ERR_OK;
  }
}

/*
** ===================================================================
**     Method      :  SPI_2_SendChar (component SynchroMaster)
**
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte SPI_2_SendChar(SPI_2_TComData Chr)
{
  if (SPI_2_OutLen == SPI_2_OUT_BUF_SIZE) { /* Is number of chars in buffer the same as the size of transmit buffer? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Enter the critical section */
  SPI_2_OutLen++;                      /* Increase number of bytes in the transmit buffer */
  *(OutPtrW++) = Chr;                  /* Store char to buffer */
  /*lint -save  -e946 Disable MISRA rule (17.2) checking. */
  if (OutPtrW >= (OutBuffer + SPI_2_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
    OutPtrW = OutBuffer;               /* Set pointer to the first item in the transmit buffer */
  }
  /*lint -restore Enable MISRA rule (17.2) checking. */
  if((SerFlag & RUNINT_FROM_TX) == 0U) { /* Transmition running? */
    (void)SPI0SR;                      /* Read the status register */
    SPI0DRL = *(OutPtrR);              /* Store char to transmitter register and start transmition */
    SerFlag |= RUNINT_FROM_TX;         /* Set RUNINT_FROM_TX flag */
  }
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI_2_RecvBlock (component SynchroMaster)
**
**     Description :
**         If any data received, this method returns the block of the
**         data and its length (and incidental error), otherwise it
**         returns error code (it does not wait for data).
**         If less than requested number of characters is received only
**         the available data is copied from the receive buffer to the
**         user specified destination and the ERR_EXEMPTY value is
**         returned.
**         This method is available only if non-zero length of input
**         buffer is defined.
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - A pointer to the block of received data
**         Size            - The size of the block
**       * Rcv             - Pointer to a variable where an actual
**                           number of copied characters is stored
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - It was not possible to read
**                           requested number of bytes from the buffer.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. If
**                           interrupt service is enabled, and input
**                           buffer allocated by the component is full,
**                           the component behaviour depends on <Input
**                           buffer size> property : if property is 0,
**                           last received data-word is preserved (and
**                           previous is overwritten), if property is
**                           greater than 0, new received data-word are
**                           ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte SPI_2_RecvBlock(SPI_2_TComData *Ptr,word Size,word *Rcv)
{
  word count = 0U;                     /* Number of received chars */
  byte errrc = ERR_OK;                 /* Most serious error */
  byte errrctmp;                       /* Last error */

  while (count < Size) {
    errrctmp = SPI_2_RecvChar(Ptr++);
    if (errrctmp>errrc) {              /* Is last error most serious than through error state? */
      errrc = errrctmp;                /* If yes then prepare error value to return */
    }
    if ((errrctmp != ERR_OK)&&(errrctmp != ERR_OVERRUN)) { /* Receiving given number of chars */
     *Rcv = count;                     /* Return number of received chars */
      return errrc;                    /* Return most serious error */
    }
    count++;
  }
  *Rcv = count;                        /* Return number of received chars */
  return errrc;                        /* Return most serious error */
}

/*
** ===================================================================
**     Method      :  SPI_2_SendBlock (component SynchroMaster)
**
**     Description :
**         Send a block of characters to the channel. This method is
**         only available if a non-zero length of output buffer is
**         defined.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Ptr             - Pointer to the block of data to send
**         Size            - Size of the block
**       * Snd             - Pointer to number of data that are sent
**                           (moved to buffer)
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - It was not possible to send
**                           requested number of bytes
** ===================================================================
*/
byte SPI_2_SendBlock(const SPI_2_TComData *Ptr,word Size,word *Snd)
{
  word count = 0U;                     /* Number of sent chars */
  bool local_OnFreeTxBuf_semaphore = OnFreeTxBuf_semaphore; /* Local copy of OnFreeTxBuf_semaphore state */

  while((count < Size) && (SPI_2_OutLen < SPI_2_OUT_BUF_SIZE)) { /* While there is some char desired to send left and output buffer is not full do */
    EnterCritical();                   /* Enter the critical section */
    OnFreeTxBuf_semaphore = TRUE;      /* Set the OnFreeTxBuf_semaphore to block OnFreeTxBuf calling */
    SPI_2_OutLen++;                    /* Increase number of bytes in the transmit buffer */
    *(OutPtrW++) = *(Ptr++);           /* Store char to the buffer */
  /*lint -save  -e946 Disable MISRA rule (17.2) checking. */
    if(OutPtrW >= (OutBuffer + SPI_2_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
      OutPtrW = OutBuffer;             /* Set the pointer to the first item in the transmit buffer */
    }
  /*lint -restore Enable MISRA rule (17.2) checking. */
    count++;                           /* Increase the count of sent data */
    if ((count == Size) || (SPI_2_OutLen == SPI_2_OUT_BUF_SIZE)) { /* Is the last desired char put into buffer or the buffer is full? */
      if (!local_OnFreeTxBuf_semaphore) { /* Was the OnFreeTxBuf_semaphore clear before enter the method? */
        OnFreeTxBuf_semaphore = FALSE; /* If yes then clear the OnFreeTxBuf_semaphore */
      }
    }
    if((SerFlag & RUNINT_FROM_TX) == 0U) { /* Transmition running? */
      (void)SPI0SR;                    /* Read the status register */
      SPI0DRL = *(OutPtrR);            /* Store char to transmitter register and start transmition */
      SerFlag |= RUNINT_FROM_TX;       /* Set RUNINT_FROM_TX flag */
    }
    ExitCritical();                    /* Exit the critical section */
  }
  *Snd = count;                        /* Return number of sent chars */
  if (count != Size) {                 /* Is the number of sent chars less then desired number of chars */
    return ERR_TXFULL;                 /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI_2_ClearRxBuf (component SynchroMaster)
**
**     Description :
**         Clears the receive buffer. This method is available only if
**         a non-zero length of input buffer is defined.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SPI_2_ClearRxBuf(void)
{
  EnterCritical();                     /* Enter the critical section */
  SPI_2_InpLen = 0U;                   /* Set number of chars in the receive buffer to 0 */
  InpPtrR = InpBuffer;                 /* Set read pointer on the first item in the receive buffer */
  InpPtrW = InpBuffer;                 /* Set write pointer on the first item in the receive buffer */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI_2_ClearTxBuf (component SynchroMaster)
**
**     Description :
**         Clears the transmit buffer. This method is only available if
**         a non-zero length of output buffer is defined.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SPI_2_ClearTxBuf(void)
{
  EnterCritical();                     /* Enter the critical section */
  SPI_2_OutLen = 0U;                   /* Set number of chars in the transmit buffer to 0 */
  OutPtrR = OutBuffer;                 /* Set read pointer on the first item in the transmit buffer */
  OutPtrW = OutBuffer;                 /* Set write pointer on the first item in the transmit buffer */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI_2_GetCharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
/*
word SPI_2_GetCharsInRxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  SPI_2_GetCharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
/*
word SPI_2_GetCharsInTxBuf(void)

**      This method is implemented as a macro. See header module. **
*/

/*
** ===================================================================
**     Method      :  SPI_2_GetError (component SynchroMaster)
**
**     Description :
**         Returns a set of errors on the channel (errors that cannot
**         be returned in given methods). The component accumulates
**         errors in a set; after calling [GetError] this set is
**         returned and cleared. This method is available only if the
**         "Interrupt service/event" property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Err             - A pointer to the returned set of errors
**     Returns     :
**         ---             - Error code (if GetError did not succeed),
**                           possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SPI_2_GetError(SPI_2_TError *Err)
{
  EnterCritical();                     /* Enter the critical section */
  Err->err = 0U;
  Err->errName.OverRun = ((ErrFlag & OVERRUN_ERR) ? 1U : 0U); /* Overrun error */
  Err->errName.RxBufOvf = ((ErrFlag & FULL_RX) ? 1U : 0U); /* Buffer overflow */
  ErrFlag = 0x00U;                     /* Reset error flags */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SPI_2_Interrupt (component SynchroMaster)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR       0x01U
#define ON_FULL_RX     0x02U
#define ON_RX_CHAR     0x04U
#define ON_FREE_TX     0x08U
#define ON_TX_CHAR     0x10U
#define ON_RX_CHAR_EXT 0x20U
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(SPI_2_Interrupt)
{
  SPI_2_TComData Data = 0U;            /* Temporary variable for data */
  byte Flags = 0U;                     /* Temporary variable for flags */
  byte Status;                         /* Temporary variable for flags */

  Status = SPI0SR;                     /* Read the device error register */
  Data = SPI0DRL;                      /* Read data from receiver */
  if(SPI_2_InpLen < SPI_2_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer lower than size of buffer? */
    SPI_2_InpLen++;                    /* Increse number of chars in the receive buffer */
    *(InpPtrW++) = Data;               /* Save received char to the receive buffer */
    /*lint -save  -e946 Disable MISRA rule (17.2) checking. */
    if(InpPtrW >= (InpBuffer + SPI_2_INP_BUF_SIZE)) { /* Is the pointer out of the receive buffer? */
      InpPtrW = InpBuffer;             /* Set pointer on the first item into the receive buffer */
    }
    /*lint -restore Enable MISRA rule (17.2) checking. */
    if(SPI_2_InpLen == SPI_2_INP_BUF_SIZE) { /* Is number of bytes in the receive buffer equal to the size of buffer? */
      Flags |= ON_FULL_RX;             /* Set flag "OnFullRxBuf" */
    }
  } else {
    SerFlag |= FULL_RX;                /* Set flag "full RX buffer" */
    Flags |= ON_ERROR;                 /* Set the OnError flag */
    ErrFlag |= FULL_RX;                /* Set the error flag for the GetError method */
  }
  SPI_2_OutLen--;                      /* Decrease number of chars in the transmit buffer */
  OutPtrR++;                           /* Increment pointer */
  /*lint -save  -e946 Disable MISRA rule (17.2) checking. */
  if (OutPtrR >= (OutBuffer + SPI_2_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
    OutPtrR = OutBuffer;               /* Set pointer on the first item into the transmit buffer */
  }
  /*lint -restore Enable MISRA rule (17.2) checking. */
  if (SPI_2_OutLen) {                  /* Is number of bytes in the transmit buffer greather then 0? */
    SPI0DRL = *(OutPtrR);              /* Store char to transmitter register */
  } else {
    SerFlag &= (byte)(~(byte)(RUNINT_FROM_TX|FULL_TX)); /* Clear "running int from TX" and "full TX buff" flags */
    if (!OnFreeTxBuf_semaphore) {      /* Is the OnFreeTXBuf flag blocked ?*/
      Flags |= ON_FREE_TX;             /* If not, set the OnFreeTXBuf flag */
    }
  }
  if(Flags & ON_ERROR) {               /* Is any error flag set? */
    __DI();
    SPI_2_OnError();                   /* If yes then invoke user event */
  } else {
    if(Flags & ON_FULL_RX) {           /* Is OnFullRxBuf flag set? */
      __DI();
      SPI_2_OnFullRxBuf();             /* If yes then invoke user event */
    }
  }
  if (Flags & ON_FREE_TX) {            /* Is flag "OnFreeTxBuf" set? */
    __DI();
    SPI_2_OnFreeTxBuf();               /* If yes then invoke user event */
  }
}

#pragma CODE_SEG SPI_2_CODE
/*
** ===================================================================
**     Method      :  SPI_2_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SPI_2_Init(void)
{
  /* SPI0CR1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  SPI0CR1 = 0x04U;                     /* Reset the device register */
  (void)SPI0SR;                        /* Read the status register */
  (void)SPI0DRL;                       /* Read the device register */
  /* SPI0BR: ??=0,SPPR2=0,SPPR1=1,SPPR0=0,??=0,SPR2=1,SPR1=0,SPR0=0 */
  SPI0BR = 0x24U;                      /* Set the baud rate register */
  /* SPI0CR2: ??=0,XFRW=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  SPI0CR2 = 0x00U;                     /* Set control register 2 */
  /* SPI0CR1: SPIE=1,SPE=1,SPTIE=0,MSTR=1,CPOL=1,CPHA=1,SSOE=0,LSBFE=0 */
  SPI0CR1 = 0xDCU;                     /* Set control register 1 */
  SerFlag = 0U;                        /* Reset all flags */
  ErrFlag = 0U;                        /* Reset all flags in mirror */
  OnFreeTxBuf_semaphore = FALSE;       /* Clear the OnFreeTxBuf_semaphore */
  SPI_2_InpLen = 0U;                   /* No char in the receive buffer */
  InpPtrR = InpBuffer;                 /* Set read pointer on the first item in the receive buffer */
  InpPtrW = InpBuffer;                 /* Set write pointer on the first item in the receive buffer */
  SPI_2_OutLen = 0U;                   /* No char in the transmit buffer */
  OutPtrR = OutBuffer;                 /* Set read pointer on the first item in the transmit buffer */
  OutPtrW = OutBuffer;                 /* Set write pointer on the first item in the transmit buffer */
}


/* END SPI_2. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
